## Tabela de Frequências com Python

In [12]:
import pandas as pd
import sqlalchemy

df = pd.read_csv("../data/points_tmw.csv", sep=',')

engine = sqlalchemy.create_engine("sqlite:///../data/tmw.db")

df.to_sql("points", engine, if_exists="replace", index=False)

5000

#### Tab. de Frequências de produtos

Para fazer o acumulado das duas frequências, estamos utilizando o método '.cumsum()'.

In [8]:
freq_produto = (df.groupby(["descProduto"])[["idTransacao"]]                                                # Frequência Absoluta
                  .count()
                  .rename(columns={"idTransacao" : "Frequência Absoluta"}))

freq_produto["Freq. Abs. Acum."] = freq_produto["Frequência Absoluta"].cumsum()                                     # Frequênia Absoluta Acumulada

freq_produto["Freq. Relativa (%)"] = freq_produto["Frequência Absoluta"] / freq_produto["Frequência Absoluta"].sum() * 100  # Frequência Relativa

freq_produto["Freq. Rel. Acum. (%)"] = freq_produto["Freq. Relativa (%)"].cumsum()                          # Frequência Relativa Acumulada

freq_produto

,Frequência Absoluta,Freq. Abs. Acum.,Freq. Relativa (%),Freq. Rel. Acum. (%)
descProduto,,,,
Airflow Lover,1,1,0.02,0.02
ChatMessage,4141,4142,82.82,82.84
Churn_10pp,31,4173,0.62,83.46
Churn_2pp,36,4209,0.72,84.18
Churn_5pp,32,4241,0.64,84.82
Daily Loot,18,4259,0.36,85.18
Lista de presença,642,4901,12.84,98.02
Presença Streak,33,4934,0.66,98.68
Resgatar Ponei,32,4966,0.64,99.32
Troca de Pontos StreamElements,28,4994,0.56,99.88
Venda de Item: 7 - Capacete de Ferro (400),6,5000,0.12,100.00

#### Tab. de Frequências de Categorias

In [ ]:
freq_cat = (df.groupby(df["descCategoriaProduto"])[["idTransacao"]]                                                 # Freq. Abs.
              .count()
              .rename(columns={"idTransacao" : "Frequência Absoluta"}))

freq_cat["Freq. Abs. Acumulada"] = freq_cat["Frequência Absoluta"].cumsum()                                         # Freq. Abs. Acumulada

freq_cat["Frequência Relativa (%)"] = freq_cat["Frequência Absoluta"] / freq_cat["Frequência Absoluta"].sum() * 100 # Frequência Relativa (%)

freq_cat["Freq. Rel. Acumulada (%)"] = freq_cat["Frequência Relativa (%)"].cumsum()                                 # Freq. Rel. Acumulada

freq_cat

,Frequência Absoluta,Freq. Abs. Acumulada,Frequência Relativa (%),Freq. Rel. Acumulada (%)
descCategoriaProduto,,,,
chat,4141,4141,82.82,82.82
churn_model,99,4240,1.98,84.80
lovers,1,4241,0.02,84.82
ponei,32,4273,0.64,85.46
present,675,4948,13.50,98.96
rpg,24,4972,0.48,99.44
streamelements,28,5000,0.56,100.00