# Medidas de Posição

Também podemos determinar as __medidas de posição__ de __medidas de tendência central__. Elas são responsáveis por mostrar onde os dados se concentram, encontrando um valor central ou um ponto de equilíbrio das dados.

In [9]:
import pandas as pd

df = pd.read_csv("../data/points_tmw.csv", sep=",")
df.head()

,idTransacao,idUsuario,dtTransacao,qtdPontos,diffMedia,descProduto,descCategoriaProduto,DataTransacao
0,83d52c4a-8585-4896-bbf3-9d9c9e885f7f,c4ade77c-f395-4d22-93c3-7a8031df9c6f,2024-11-08 12:34:58,1,"17,15119396",ChatMessage,chat,08/11/2024
1,64feebd3-70d1-42f5-ba90-3d89e12b7e98,65662aff-44d6-4f06-b9d9-07445c6e5943,2024-01-31 12:02:10,1,"17,15119396",ChatMessage,chat,31/01/2024
2,e242114e-3cb1-41a0-b16b-d7ecb04365c9,a7649e0c-92dd-42fe-bb36-d6f0aaaa8638,2024-03-26 12:34:32,1,"17,15119396",ChatMessage,chat,26/03/2024
3,35f3adc9-9d9b-464b-8c53-c96537b2f573,1856963a-84cb-453e-a139-eb7d8d9b3255,2024-12-10 11:36:37,50,"2012,293994",Lista de presença,present,10/12/2024
4,8cd5864e-401d-4e84-be85-af90bc3f7feb,65662aff-44d6-4f06-b9d9-07445c6e5943,2024-05-23 11:50:09,1,"17,15119396",ChatMessage,chat,23/05/2024

### Calculando medidas de posição:

In [5]:
minimo = df["qtdPontos"].min()
print(f"Mínimo: {minimo}")

media = df["qtdPontos"].mean()
print(f"Média: {media}")

quartil_1 = df["qtdPontos"].quantile(0.25)
print(f"1º Quartil: {quartil_1}")

mediana = df["qtdPontos"].median() # ou poderíamos usar '.quantile(0.5)
print(f"Mediana: {mediana}")

quartil_3 = df["qtdPontos"].quantile(0.75)
print(f"3º Quartil: {quartil_3}")

maximo = df["qtdPontos"].max()
print(f"Máximo: {maximo}")

Mínimo: -1000
Média: 5.1414
1º Quartil: 1.0
Mediana: 1.0
3º Quartil: 1.0
Máximo: 1000

Ou realizando de forma mais rápida através do método '.describe()'

In [6]:
df["qtdPontos"].describe()

count    5000.000000
mean        5.141400
std        85.445747
min     -1000.000000
25%         1.000000
50%         1.000000
75%         1.000000
max      1000.000000
Name: qtdPontos, dtype: float64

### Calculando a partir de agrupamentos:

In [16]:
usuarios = (df.groupby("idUsuario")
              .agg({"idTransacao" : "count",
                    "qtdPontos" : "sum"})
              .reset_index())

usuarios

                                idUsuario  idTransacao  qtdPontos
0    000ff655-fa9f-4baa-a108-47f581ec52a1            5          5
1    0033b737-8235-4c0f-9801-dc4ca185af00           13        161
2    00a6d4c8-38e5-4e92-981e-4e4ac5084546            8       -400
3    0122142b-464c-414a-9aad-e901f492a1a3            1          1
4    012bc897-e45c-4e6a-a742-7e00fa2e59e5            1         50
..                                    ...          ...        ...
852  fe391f8e-c2eb-4bd9-b8a5-e284151deb6a            1         50
853  fe58b66c-64db-44fd-b8cb-8966aeac3bd3            2          2
854  fe59fd95-d131-4d50-bb6e-10cdfa7d5f47            2          2
855  feb1a34d-202a-4224-a1b3-0e737b12dd4d            3        101
856  fecbdf63-3bf4-44e5-8b1a-0acc9d963603            1          1

[857 rows x 3 columns]

'.describe()' para colunas específicas.

In [17]:
df[['idTransacao', 'qtdPontos']].describe()

         qtdPontos
count  5000.000000
mean      5.141400
std      85.445747
min   -1000.000000
25%       1.000000
50%       1.000000
75%       1.000000
max    1000.000000